- name: RSS
  resultset:
    - name: RSS
      filters:
        ors:
          - type: simple
            object: content
            # value: '<rss version="'
            value: '<rss'
          - type: simple
            object: content
            value: 'http://api.npr.org/nprml'

- name: ATOM
  resultset:
    - name: ATOM
      filters:
        ands:
          - type: simple
            object: content
            value: 'http://www.w3.org/2005/Atom'
          - type: simple
            object: content
            value: '<feed'
            # exclude the opensearch namespaced ones
          - type: xpath
            object: content
            value: 'count(/*/namespace::*[. = "http://a9.com/-/spec/opensearch/1.1/"]) < 1'
