- name: RDF
  dataset:
    - name: RDF
      request: ''
      filters:
        ands:
          - type: xpath
            object: content
            value: '/*[local-name()="RDF"]'
          - type: simple
            object: content
            value: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
          - type: simple
            object: content
            value: '<dcat:Dataset rdf:about='
      language:
        checks:
          ors:
            - type: xpath
              object: content
              value: '@xml:lang'
